# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime-MTARR.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.google.transit.realtime import gtfs_realtime_pb2 as com_dot_google_dot_transit_dot_realtime_dot_gtfs__realtime__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gtfs-realtime-MTARR.proto',
  package='transit_realtime',
  syntax='proto2',
  serialized_options=b'\n\033com.google.transit.realtime',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19gtfs-realtime-MTARR.proto\x12\x10transit_realtime\x1a/com/google/transit/realtime/gtfs-realtime.proto\"?\n\x19MtaRailroadStopTimeUpdate\x12\r\n\x05track\x18\x01 \x01(\t\x12\x13\n\x0btrainStatus\x18\x02 \x01(\t\"\xe9\x03\n\x1aMtaRailroadCarriageDetails\x12\x1b\n\x10\x62icycles_allowed\x18\x01 \x01(\x05:\x01\x30\x12\x16\n\x0e\x63\x61rriage_class\x18\x02 \x01(\t\x12j\n\x0equiet_carriage\x18\x03 \x01(\x0e\x32:.transit_realtime.MtaRailroadCarriageDetails.QuietCarriage:\x16UNKNOWN_QUIET_CARRIAGE\x12s\n\x11toilet_facilities\x18\x04 \x01(\x0e\x32=.transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities:\x19UNKNOWN_TOILET_FACILITIES\"W\n\rQuietCarriage\x12\x1a\n\x16UNKNOWN_QUIET_CARRIAGE\x10\x00\x12\x12\n\x0eQUIET_CARRIAGE\x10\x01\x12\x16\n\x12NOT_QUIET_CARRIAGE\x10\x02\"\\\n\x10ToiletFacilities\x12\x1d\n\x19UNKNOWN_TOILET_FACILITIES\x10\x00\x12\x12\n\x0eTOILET_ONBOARD\x10\x01\x12\x15\n\x11NO_TOILET_ONBOARD\x10\x02:\x80\x01\n\x1dmta_railroad_stop_time_update\x12+.transit_realtime.TripUpdate.StopTimeUpdate\x18\xed\x07 \x01(\x0b\x32+.transit_realtime.MtaRailroadStopTimeUpdate:w\n\x1dmta_railroad_carriage_details\x12!.transit_realtime.VehiclePosition\x18\xed\x07 \x01(\x0b\x32,.transit_realtime.MtaRailroadCarriageDetailsB\x1d\n\x1b\x63om.google.transit.realtime'
  ,
  dependencies=[com_dot_google_dot_transit_dot_realtime_dot_gtfs__realtime__pb2.DESCRIPTOR,])


MTA_RAILROAD_STOP_TIME_UPDATE_FIELD_NUMBER = 1005
mta_railroad_stop_time_update = _descriptor.FieldDescriptor(
  name='mta_railroad_stop_time_update', full_name='transit_realtime.mta_railroad_stop_time_update', index=0,
  number=1005, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
MTA_RAILROAD_CARRIAGE_DETAILS_FIELD_NUMBER = 1005
mta_railroad_carriage_details = _descriptor.FieldDescriptor(
  name='mta_railroad_carriage_details', full_name='transit_realtime.mta_railroad_carriage_details', index=1,
  number=1005, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

_MTARAILROADCARRIAGEDETAILS_QUIETCARRIAGE = _descriptor.EnumDescriptor(
  name='QuietCarriage',
  full_name='transit_realtime.MtaRailroadCarriageDetails.QuietCarriage',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_QUIET_CARRIAGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='QUIET_CARRIAGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOT_QUIET_CARRIAGE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=470,
  serialized_end=557,
)
_sym_db.RegisterEnumDescriptor(_MTARAILROADCARRIAGEDETAILS_QUIETCARRIAGE)

_MTARAILROADCARRIAGEDETAILS_TOILETFACILITIES = _descriptor.EnumDescriptor(
  name='ToiletFacilities',
  full_name='transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TOILET_FACILITIES', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TOILET_ONBOARD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NO_TOILET_ONBOARD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=559,
  serialized_end=651,
)
_sym_db.RegisterEnumDescriptor(_MTARAILROADCARRIAGEDETAILS_TOILETFACILITIES)


_MTARAILROADSTOPTIMEUPDATE = _descriptor.Descriptor(
  name='MtaRailroadStopTimeUpdate',
  full_name='transit_realtime.MtaRailroadStopTimeUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='track', full_name='transit_realtime.MtaRailroadStopTimeUpdate.track', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trainStatus', full_name='transit_realtime.MtaRailroadStopTimeUpdate.trainStatus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=159,
)


_MTARAILROADCARRIAGEDETAILS = _descriptor.Descriptor(
  name='MtaRailroadCarriageDetails',
  full_name='transit_realtime.MtaRailroadCarriageDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bicycles_allowed', full_name='transit_realtime.MtaRailroadCarriageDetails.bicycles_allowed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='carriage_class', full_name='transit_realtime.MtaRailroadCarriageDetails.carriage_class', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quiet_carriage', full_name='transit_realtime.MtaRailroadCarriageDetails.quiet_carriage', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toilet_facilities', full_name='transit_realtime.MtaRailroadCarriageDetails.toilet_facilities', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MTARAILROADCARRIAGEDETAILS_QUIETCARRIAGE,
    _MTARAILROADCARRIAGEDETAILS_TOILETFACILITIES,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=651,
)

_MTARAILROADCARRIAGEDETAILS.fields_by_name['quiet_carriage'].enum_type = _MTARAILROADCARRIAGEDETAILS_QUIETCARRIAGE
_MTARAILROADCARRIAGEDETAILS.fields_by_name['toilet_facilities'].enum_type = _MTARAILROADCARRIAGEDETAILS_TOILETFACILITIES
_MTARAILROADCARRIAGEDETAILS_QUIETCARRIAGE.containing_type = _MTARAILROADCARRIAGEDETAILS
_MTARAILROADCARRIAGEDETAILS_TOILETFACILITIES.containing_type = _MTARAILROADCARRIAGEDETAILS
DESCRIPTOR.message_types_by_name['MtaRailroadStopTimeUpdate'] = _MTARAILROADSTOPTIMEUPDATE
DESCRIPTOR.message_types_by_name['MtaRailroadCarriageDetails'] = _MTARAILROADCARRIAGEDETAILS
DESCRIPTOR.extensions_by_name['mta_railroad_stop_time_update'] = mta_railroad_stop_time_update
DESCRIPTOR.extensions_by_name['mta_railroad_carriage_details'] = mta_railroad_carriage_details
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MtaRailroadStopTimeUpdate = _reflection.GeneratedProtocolMessageType('MtaRailroadStopTimeUpdate', (_message.Message,), {
  'DESCRIPTOR' : _MTARAILROADSTOPTIMEUPDATE,
  '__module__' : 'gtfs_realtime_MTARR_pb2'
  # @@protoc_insertion_point(class_scope:transit_realtime.MtaRailroadStopTimeUpdate)
  })
_sym_db.RegisterMessage(MtaRailroadStopTimeUpdate)

MtaRailroadCarriageDetails = _reflection.GeneratedProtocolMessageType('MtaRailroadCarriageDetails', (_message.Message,), {
  'DESCRIPTOR' : _MTARAILROADCARRIAGEDETAILS,
  '__module__' : 'gtfs_realtime_MTARR_pb2'
  # @@protoc_insertion_point(class_scope:transit_realtime.MtaRailroadCarriageDetails)
  })
_sym_db.RegisterMessage(MtaRailroadCarriageDetails)

mta_railroad_stop_time_update.message_type = _MTARAILROADSTOPTIMEUPDATE
com_dot_google_dot_transit_dot_realtime_dot_gtfs__realtime__pb2.TripUpdate.StopTimeUpdate.RegisterExtension(mta_railroad_stop_time_update)
mta_railroad_carriage_details.message_type = _MTARAILROADCARRIAGEDETAILS
com_dot_google_dot_transit_dot_realtime_dot_gtfs__realtime__pb2.VehiclePosition.RegisterExtension(mta_railroad_carriage_details)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
